import * as THREE from "three";

const $=id=>document.getElementById(id), canvas=$("gameCanvas");
const ui={hud:$("hud"),objective:$("objective"),cores:$("cores"),time:$("time"),message:$("message"),danger:$("danger"),menu:$("menu"),menuTitle:$("menuTitle"),menuStory:$("menuStory"),missionTitle:$("missionTitle"),missionText:$("missionText"),controlsText:$("controlsText"),startBtn:$("startBtn"),desktopNote:$("desktopNote"),langEs:$("langEs"),langEn:$("langEn"),pause:$("pause"),pauseTitle:$("pauseTitle"),pauseText:$("pauseText"),resumeBtn:$("resumeBtn"),restartPause:$("restartPause"),end:$("end"),endTitle:$("endTitle"),endText:$("endText"),endStats:$("endStats"),restartBtn:$("restartBtn"),loading:$("loading"),unsupported:$("unsupported")};

const fmt=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,"0")}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,"0")}`;
const T={
 es:{title:"ESCAPA DE LA BASE ANUNNAKI",story:"Despiertas en el complejo subterráneo A-17. Las luces de emergencia siguen activas, pero el personal ha desaparecido. Algo recorre los pasillos y la única salida permanece sellada.",missionTitle:"MISIÓN",mission:"Encuentra los 3 núcleos de energía, reactiva el portal de evacuación y escapa antes de que el Guardián te alcance.",start:"ENTRAR A LA BASE",resume:"CONTINUAR",restart:"REINICIAR PARTIDA",paused:"PAUSA",pauseText:"El juego se pausó al liberar el ratón.",desktop:"Recomendado para computadora con teclado y ratón.",controls:[["WASD","Moverse"],["RATÓN","Mirar"],["SHIFT","Correr"],["F","Linterna"],["ESC","Pausa"],["R","Reiniciar al perder"]],objective:"Objetivo: encuentra los 3 núcleos y llega al portal.",cores:n=>`NÚCLEOS ${n}/3`,time:s=>`TIEMPO ${fmt(s)}`,pickup:n=>`Núcleo recuperado. ${n}/3`,first:"Has activado algo en la base. Ya no estás solo.",all:"Los 3 núcleos están activos. El portal de evacuación está listo.",locked:n=>`El portal necesita 3 núcleos. Te faltan ${3-n}.`,danger:"⚠ GUARDIÁN CERCA",winTitle:"ESCAPASTE",winText:"El portal se cerró detrás de ti. El archivo A-17 queda registrado como incidente PARALOGIA.",loseTitle:"TE ENCONTRÓ",loseText:"La señal se perdió dentro de la base.",stats:s=>`Tiempo de escape: <strong>${fmt(s)}</strong><br>Núcleos recuperados: <strong>3/3</strong>`,retry:"VOLVER A INTENTAR",flashOn:"Linterna encendida",flashOff:"Linterna apagada"},
 en:{title:"ESCAPE THE ANUNNAKI BASE",story:"You wake inside underground complex A-17. Emergency lights are still running, but the personnel are gone. Something moves through the corridors and the only exit remains sealed.",missionTitle:"MISSION",mission:"Find the 3 energy cores, reactivate the evacuation portal and escape before the Guardian reaches you.",start:"ENTER THE BASE",resume:"CONTINUE",restart:"RESTART RUN",paused:"PAUSED",pauseText:"The game paused when the mouse was released.",desktop:"Desktop computer with keyboard and mouse recommended.",controls:[["WASD","Move"],["MOUSE","Look"],["SHIFT","Run"],["F","Flashlight"],["ESC","Pause"],["R","Restart after defeat"]],objective:"Objective: find all 3 cores and reach the portal.",cores:n=>`CORES ${n}/3`,time:s=>`TIME ${fmt(s)}`,pickup:n=>`Core recovered. ${n}/3`,first:"You activated something in the base. You are no longer alone.",all:"All 3 cores are active. The evacuation portal is ready.",locked:n=>`The portal needs 3 cores. ${3-n} remaining.`,danger:"⚠ GUARDIAN NEARBY",winTitle:"YOU ESCAPED",winText:"The portal closed behind you. File A-17 is now registered as a PARALOGIA incident.",loseTitle:"IT FOUND YOU",loseText:"The signal was lost inside the base.",stats:s=>`Escape time: <strong>${fmt(s)}</strong><br>Cores recovered: <strong>3/3</strong>`,retry:"TRY AGAIN",flashOn:"Flashlight on",flashOff:"Flashlight off"}
};

let lang="es",renderer,scene,camera,clock,started=false,paused=false,ended=false,startTime=0,elapsed=0,msgTimer=0,yaw=0,pitch=0,flashOn=true;
const keys={},N=17,CELL=4.4,ORIGIN=-((N-1)*CELL)/2,WALL_H=3.7,WALL_T=.24,PLAYER_H=1.62,RADIUS=.34,WALK=4.4,RUN=7.2;
let maze=[],wallBoxes=[],relics=[],relicCount=0,portal,portalRing,portalLight,guardian,guardianCell={r:N-1,c:Math.floor(N/2)},guardianActive=false,guardianPath=[],pathTimer=0,audioCtx=null;

function setLang(l){lang=l;document.documentElement.lang=l;ui.langEs.classList.toggle("active",l==="es");ui.langEn.classList.toggle("active",l==="en");const t=T[l];ui.menuTitle.textContent=t.title;ui.menuStory.textContent=t.story;ui.missionTitle.textContent=t.missionTitle;ui.missionText.textContent=t.mission;ui.startBtn.textContent=t.start;ui.desktopNote.textContent=t.desktop;ui.pauseTitle.textContent=t.paused;ui.pauseText.textContent=t.pauseText;ui.resumeBtn.textContent=t.resume;ui.restartPause.textContent=t.restart;ui.restartBtn.textContent=t.retry;ui.controlsText.innerHTML=t.controls.map(([k,v])=>`<div class="control"><kbd>${k}</kbd><span>${v}</span></div>`).join("");updateHUD()}
ui.langEs.onclick=()=>setLang("es");ui.langEn.onclick=()=>setLang("en");

function rng(seed=92731){let v=seed>>>0;return()=>{v+=0x6D2B79F5;let t=v;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function makeMaze(){const r=rng(20261005);maze=Array.from({length:N},()=>Array.from({length:N},()=>({seen:false,w:{n:true,e:true,s:true,w:true}})));const st=[{r:0,c:0}];maze[0][0].seen=true;while(st.length){const a=st[st.length-1],o=[];if(a.r>0&&!maze[a.r-1][a.c].seen)o.push(["n",a.r-1,a.c,"s"]);if(a.c<N-1&&!maze[a.r][a.c+1].seen)o.push(["e",a.r,a.c+1,"w"]);if(a.r<N-1&&!maze[a.r+1][a.c].seen)o.push(["s",a.r+1,a.c,"n"]);if(a.c>0&&!maze[a.r][a.c-1].seen)o.push(["w",a.r,a.c-1,"e"]);if(!o.length){st.pop();continue}const [d,nr,nc,op]=o[Math.floor(r()*o.length)];maze[a.r][a.c].w[d]=false;maze[nr][nc].w[op]=false;maze[nr][nc].seen=true;st.push({r:nr,c:nc})}for(let i=0;i<18;i++){const rr=1+Math.floor(r()*(N-2)),c=1+Math.floor(r()*(N-2));if(r()<.5){maze[rr][c].w.e=false;maze[rr][c+1].w.w=false}else{maze[rr][c].w.s=false;maze[rr+1][c].w.n=false}}}
const cellWorld=(r,c)=>new THREE.Vector3(ORIGIN+c*CELL,PLAYER_H,ORIGIN+r*CELL);
const worldCell=p=>({c:THREE.MathUtils.clamp(Math.round((p.x-ORIGIN)/CELL),0,N-1),r:THREE.MathUtils.clamp(Math.round((p.z-ORIGIN)/CELL),0,N-1)});

function panelTexture(){const c=document.createElement("canvas");c.width=c.height=512;const x=c.getContext("2d");x.fillStyle="#111715";x.fillRect(0,0,512,512);x.strokeStyle="#25322d";x.lineWidth=5;for(let i=0;i<=512;i+=64){x.beginPath();x.moveTo(i,0);x.lineTo(i,512);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(512,i);x.stroke()}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(18,18);t.colorSpace=THREE.SRGBColorSpace;return t}
function wall(x,z,w,d,m){const q=new THREE.Mesh(new THREE.BoxGeometry(w,WALL_H,d),m);q.position.set(x,WALL_H/2,z);q.castShadow=q.receiveShadow=true;scene.add(q);q.updateMatrixWorld();wallBoxes.push(new THREE.Box3().setFromObject(q))}
function buildBase(){const floor=new THREE.Mesh(new THREE.PlaneGeometry(N*CELL,N*CELL),new THREE.MeshStandardMaterial({map:panelTexture(),color:0x77847e,roughness:.82,metalness:.28}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const ceil=new THREE.Mesh(new THREE.PlaneGeometry(N*CELL,N*CELL),new THREE.MeshStandardMaterial({color:0x0a0f0d,roughness:.9,metalness:.2,side:THREE.DoubleSide}));ceil.rotation.x=Math.PI/2;ceil.position.y=WALL_H;scene.add(ceil);const wm=new THREE.MeshStandardMaterial({color:0x27312d,roughness:.58,metalness:.58});for(let r=0;r<N;r++)for(let c=0;c<N;c++){const x=ORIGIN+c*CELL,z=ORIGIN+r*CELL,q=maze[r][c];if(q.w.n)wall(x,z-CELL/2,CELL+WALL_T,WALL_T,wm);if(q.w.w)wall(x-CELL/2,z,WALL_T,CELL+WALL_T,wm);if(r===N-1&&q.w.s)wall(x,z+CELL/2,CELL+WALL_T,WALL_T,wm);if(c===N-1&&q.w.e)wall(x+CELL/2,z,WALL_T,CELL+WALL_T,wm)}const em=new THREE.MeshStandardMaterial({color:0xa7ffcf,emissive:0x36ff91,emissiveIntensity:2.2,roughness:.3});for(let r=1;r<N;r+=4)for(let c=1;c<N;c+=4){const p=cellWorld(r,c),s=new THREE.Mesh(new THREE.BoxGeometry(1.35,.05,.13),em);s.position.set(p.x,WALL_H-.06,p.z);scene.add(s);const l=new THREE.PointLight(0x42ff9a,4.2,12,2);l.position.set(p.x,WALL_H-.35,p.z);scene.add(l)}for(const [r,c] of [[N-2,1],[N-4,N-3],[8,8]]){const p=cellWorld(r,c),l=new THREE.PointLight(0xff314e,3.2,10,2);l.position.set(p.x,2.7,p.z);scene.add(l)}const count=700,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*N*CELL;pos[i*3+1]=Math.random()*(WALL_H-.2)+.1;pos[i*3+2]=(Math.random()-.5)*N*CELL}const g=new THREE.BufferGeometry();g.setAttribute("position",new THREE.BufferAttribute(pos,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xa6c9b7,size:.025,transparent:true,opacity:.22})))}
function relic(r,c,i){const g=new THREE.Group(),core=new THREE.Mesh(new THREE.OctahedronGeometry(.52,0),new THREE.MeshStandardMaterial({color:0x63ffbb,emissive:0x1cff88,emissiveIntensity:2.6,metalness:.72,roughness:.2}));g.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(.83,.055,10,36),new THREE.MeshBasicMaterial({color:0x7dffd0}));ring.rotation.x=Math.PI/2;g.add(ring);g.add(new THREE.PointLight(0x4dffad,5.5,9,2));const p=cellWorld(r,c);g.position.set(p.x,1.18,p.z);g.userData={collected:false,phase:i*1.8};scene.add(g);relics.push(g)}
function makePortal(){const p=cellWorld(N-1,N-1);portal=new THREE.Group();portal.position.set(p.x,1.45,p.z);portalRing=new THREE.Mesh(new THREE.TorusGeometry(1.12,.12,14,64),new THREE.MeshStandardMaterial({color:0x41504a,emissive:0x07130d,emissiveIntensity:.3,metalness:.8,roughness:.28}));portalRing.rotation.y=Math.PI/2;portal.add(portalRing);const inner=new THREE.Mesh(new THREE.CircleGeometry(.98,48),new THREE.MeshBasicMaterial({color:0x0a1712,transparent:true,opacity:.6,side:THREE.DoubleSide}));inner.rotation.y=Math.PI/2;portal.add(inner);portalLight=new THREE.PointLight(0x4dffad,.5,7,2);portal.add(portalLight);scene.add(portal)}
function makeGuardian(){guardian=new THREE.Group();guardian.add(new THREE.Mesh(new THREE.IcosahedronGeometry(.58,1),new THREE.MeshStandardMaterial({color:0x2b090d,emissive:0xff1738,emissiveIntensity:2.7,metalness:.75,roughness:.25})));const a=new THREE.Mesh(new THREE.TorusGeometry(.86,.05,10,42),new THREE.MeshBasicMaterial({color:0xff5369}));a.rotation.x=Math.PI/2.3;guardian.add(a);const b=a.clone();b.rotation.x=.35;b.rotation.y=Math.PI/2;guardian.add(b);guardian.add(new THREE.PointLight(0xff2347,7,11,2));const p=cellWorld(guardianCell.r,guardianCell.c);guardian.position.set(p.x,1.35,p.z);guardian.visible=false;scene.add(guardian)}
function collide(p){const b=new THREE.Box3(new THREE.Vector3(p.x-RADIUS,.15,p.z-RADIUS),new THREE.Vector3(p.x+RADIUS,PLAYER_H+.25,p.z+RADIUS));return wallBoxes.some(w=>w.intersectsBox(b))}

function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x010604);scene.fog=new THREE.FogExp2(0x020806,.055);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,160);camera.rotation.order="YXZ";scene.add(camera);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;scene.add(new THREE.HemisphereLight(0x3b6652,0x040605,.42));const f=new THREE.SpotLight(0xe9fff2,10.5,24,Math.PI/7,.46,1.4);f.castShadow=true;const target=new THREE.Object3D();target.position.set(0,0,-5);camera.add(target);f.target=target;camera.add(f);camera.userData.flash=f;makeMaze();buildBase();relic(0,N-1,0);relic(N-1,0,1);relic(8,10,2);makePortal();makeGuardian();camera.position.copy(cellWorld(0,0));clock=new THREE.Clock()}

function audio(){if(audioCtx)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type="sine";o.frequency.value=47;f.type="lowpass";f.frequency.value=180;g.gain.value=.025;o.connect(f);f.connect(g);g.connect(audioCtx.destination);o.start()}catch{}}
function beep(freq=440,d=.12,gain=.06){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function say(s,d=2.5){ui.message.textContent=s;ui.message.classList.add("show");msgTimer=d}function updateHUD(){if(!ui.objective)return;ui.objective.textContent=T[lang].objective;ui.cores.textContent=T[lang].cores(relicCount);ui.time.textContent=T[lang].time(elapsed)}
function activateGuardian(){if(guardianActive)return;guardianActive=true;guardian.visible=true;say(T[lang].first,4.2)}function activatePortal(){portalRing.material.color.setHex(0x55ffaf);portalRing.material.emissive.setHex(0x24ff8b);portalRing.material.emissiveIntensity=2.8;portalLight.intensity=7.5;say(T[lang].all,4);beep(880,.18,.09);setTimeout(()=>beep(1180,.22,.07),140)}
function collect(dt,t){for(const q of relics){if(q.userData.collected)continue;q.rotation.y+=dt*1.2;q.children[1].rotation.z+=dt*.7;q.position.y=1.18+Math.sin(t*2+q.userData.phase)*.12;if(camera.position.distanceTo(q.position)<1.05){q.userData.collected=true;q.visible=false;relicCount++;beep(620+relicCount*120,.18,.1);say(T[lang].pickup(relicCount));if(relicCount===1)activateGuardian();if(relicCount===3)activatePortal();updateHUD()}}}
function neigh(r,c){const q=maze[r][c],a=[];if(!q.w.n&&r>0)a.push({r:r-1,c});if(!q.w.e&&c<N-1)a.push({r,c:c+1});if(!q.w.s&&r<N-1)a.push({r:r+1,c});if(!q.w.w&&c>0)a.push({r,c:c-1});return a}
function path(a,b){const k=p=>`${p.r},${p.c}`,q=[a],came=new Map([[k(a),null]]);while(q.length){const x=q.shift();if(x.r===b.r&&x.c===b.c){const out=[];let z=k(x);while(z){const [r,c]=z.split(",").map(Number);out.push({r,c});const p=came.get(z);z=p?k(p):null}return out.reverse()}for(const n of neigh(x.r,x.c)){const nk=k(n);if(!came.has(nk)){came.set(nk,x);q.push(n)}}}return[]}
function updateGuardian(dt,t){if(!guardianActive||ended){ui.danger.classList.add("hidden");return}pathTimer-=dt;const pc=worldCell(camera.position);if(pathTimer<=0){guardianCell=worldCell(guardian.position);guardianPath=path(guardianCell,pc);pathTimer=.65}if(guardianPath.length>1){const n=guardianPath[1],target=cellWorld(n.r,n.c);target.y=1.35;const dist=guardian.position.distanceTo(target);if(dist<.12){guardianPath.shift();guardianCell=n}else guardian.position.addScaledVector(target.sub(guardian.position).normalize(),(relicCount>=2?2.45:2.05)*dt)}guardian.rotation.y+=dt*1.9;guardian.children[1].rotation.z+=dt*1.8;guardian.children[2].rotation.x+=dt*1.3;guardian.position.y=1.35+Math.sin(t*3.1)*.14;const d=guardian.position.distanceTo(camera.position);ui.danger.textContent=T[lang].danger;ui.danger.classList.toggle("hidden",d>9);if(d<1.15)finish(false)}
function checkPortal(t){portal.rotation.y=Math.sin(t*.55)*.06;if(relicCount===3)portalRing.rotation.z+=.012;const d=camera.position.distanceTo(portal.position);if(d<1.3){if(relicCount===3)finish(true);else if(msgTimer<=.15)say(T[lang].locked(relicCount),2)}}
function move(dt){if(!started||paused||ended||document.pointerLockElement!==canvas)return;let f=0,s=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyD)s++;if(keys.KeyA)s--;if(!f&&!s)return;const m=Math.hypot(f,s)||1;f/=m;s/=m;const speed=(keys.ShiftLeft||keys.ShiftRight)?RUN:WALK,fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw),dx=(fx*f+rx*s)*speed*dt,dz=(fz*f+rz*s)*speed*dt;const x=camera.position.clone();x.x+=dx;if(!collide(x))camera.position.x=x.x;const z=camera.position.clone();z.z+=dz;if(!collide(z))camera.position.z=z.z;camera.position.y=PLAYER_H}
function finish(win){if(ended)return;ended=true;elapsed=(performance.now()-startTime)/1000;document.exitPointerLock?.();ui.hud.classList.add("hidden");ui.endTitle.textContent=win?T[lang].winTitle:T[lang].loseTitle;ui.endText.textContent=win?T[lang].winText:T[lang].loseText;ui.endStats.innerHTML=win?T[lang].stats(elapsed):`${T[lang].cores(relicCount)}<br>${T[lang].time(elapsed)}`;ui.end.classList.remove("hidden");beep(win?740:90,win?.22:.5,.09)}
function reset(){relicCount=0;guardianActive=false;guardianPath=[];ended=false;paused=false;elapsed=0;startTime=performance.now();for(const q of relics){q.userData.collected=false;q.visible=true}camera.position.copy(cellWorld(0,0));yaw=pitch=0;camera.rotation.set(0,0,0);guardian.visible=false;guardianCell={r:N-1,c:Math.floor(N/2)};guardian.position.copy(cellWorld(guardianCell.r,guardianCell.c));guardian.position.y=1.35;portalRing.material.color.setHex(0x41504a);portalRing.material.emissive.setHex(0x07130d);portalRing.material.emissiveIntensity=.3;portalLight.intensity=.5;ui.end.classList.add("hidden");ui.pause.classList.add("hidden");ui.hud.classList.remove("hidden");updateHUD()}
function start(){audio();audioCtx?.resume?.();started=true;reset();ui.menu.classList.add("hidden");canvas.requestPointerLock()}function resume(){paused=false;ui.pause.classList.add("hidden");canvas.requestPointerLock()}
ui.startBtn.onclick=start;ui.resumeBtn.onclick=resume;ui.restartBtn.onclick=()=>{reset();canvas.requestPointerLock()};ui.restartPause.onclick=()=>{reset();canvas.requestPointerLock()};
document.addEventListener("pointerlockchange",()=>{if(!started||ended)return;const lock=document.pointerLockElement===canvas;paused=!lock;ui.pause.classList.toggle("hidden",lock)});document.addEventListener("mousemove",e=>{if(document.pointerLockElement!==canvas||paused||ended)return;const k=.0021;yaw-=e.movementX*k;pitch=THREE.MathUtils.clamp(pitch-e.movementY*k,-Math.PI/2+.08,Math.PI/2-.08);camera.rotation.y=yaw;camera.rotation.x=pitch});document.addEventListener("keydown",e=>{keys[e.code]=true;if(e.code==="KeyF"&&started&&!ended){flashOn=!flashOn;camera.userData.flash.visible=flashOn;say(flashOn?T[lang].flashOn:T[lang].flashOff,1.2)}if(e.code==="KeyR"&&ended){reset();canvas.requestPointerLock()}});document.addEventListener("keyup",e=>keys[e.code]=false);addEventListener("resize",()=>{if(!camera)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});
function loop(){requestAnimationFrame(loop);if(!renderer)return;const dt=Math.min(clock.getDelta(),.05),t=performance.now()/1000;if(started&&!paused&&!ended){elapsed=(performance.now()-startTime)/1000;move(dt);collect(dt,t);updateGuardian(dt,t);checkPortal(t);updateHUD();if(msgTimer>0){msgTimer-=dt;if(msgTimer<=0)ui.message.classList.remove("show")}}renderer.render(scene,camera)}
function webgl(){try{const c=document.createElement("canvas");return !!(window.WebGLRenderingContext&&(c.getContext("webgl")||c.getContext("experimental-webgl")))}catch{return false}}
function boot(){setLang("es");if(!webgl()){ui.loading.classList.add("hidden");ui.menu.classList.add("hidden");ui.unsupported.classList.remove("hidden");return}try{init();ui.loading.classList.add("hidden");loop()}catch(e){console.error(e);ui.loading.innerHTML="<strong>No se pudo iniciar el juego.</strong><span>Recarga la página o prueba con otro navegador.</span>"}}
boot();
